###############################################################################
###############################################################################
#
#              [ONETOOL v0.0.1; 06 Jul 2016] -- 6 Jul 2016 03:53:40
#
# Remember you have agreed to add an appropriate statement (including the
# NIH grant number) under "acknowledgments" in any publication of results
# obtained by using this program. Suggested wording is:
#
# "(Some of)The results of this paper were obtained by using the software
# package ONETOOL, which was supported by the National Research Foundation
# of Korea Grant funded by Korean Government (NRF-2014S1A2A2028559)."
#
###############################################################################
###############################################################################

==============================================================================
|                     General Statistics: All Pedigrees                      |
|============================================================================|
|                 |    Count| Mean Size +/- Std. Dev. (     Min.,      Max.) |
|----------------------------------------------------------------------------|
|Pedigrees        |        1|     37.00 +/-      ---  (       37,        37) |
|============================================================================|
|Generation Statistics||  Nuc  Family Statistics ||  Inh  Vector Bit Stats   |
|# of Gens | # of Peds|| # of Nuc Fams |# of Peds||   # of Bits   |# of Peds |
|----------------------------------------------------------------------------|
|         6|         1||      9 -    16|        1||     33 -    64|         1|
|============================================================================|
|                 |    Count| Mean Size +/- Std. Dev. (     Min.,      Max.) |
|----------------------------------------------------------------------------|
|Sibships         |       11|      2.27 +/-      1.66 (        1,         7) |
|============================================================================|
|Constituent   |          || Marriage    |          ||             |         |
|Pedigrees     |         1|| Rings       |         0|| Loops       |        0|
|============================================================================|
|Pairs                   |       Count||  Individuals           |       Count|
|----------------------------------------------------------------------------|
|Parent/Off              |          50||  Male                  |          20|
|Sib/Sib                 |          31||  Female                |          17|
|Sis/Sis                 |           8||  Unknown               |           0|
|Bro/Bro                 |           4||        Total           |          37|
|Bro/Sis                 |          19||                        |            |
|Grandp.                 |          48||  Founder               |          12|
|Avunc.                  |          68||  Non-founder           |          25|
|Half Sib                |           0||  Singleton             |           0|
|Cousin                  |          44||        Total           |          37|
|============================================================================|
|                      Individuals With Multiple Mates                       |
|none                                                                        |
|============================================================================|
|                        Consanguineous Mating Pairs                         |
|none                                                                        |
==============================================================================
