#! Type Probability File, version 1.1.
#  This file is automatically generated.  Do not edit!

Model="test_segreg_AGE",title="SEGREG Analysis 1"
{
  alleles
  {
    A = 0.5
    B = 0.5
  }
  pedigree="1"
  {
    individual="2171-JLH-1", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-10", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-11", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-12", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-13", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-14", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-15", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-16", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-17", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-18", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-19", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-2", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-20", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-21", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-22", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-23", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-24", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-25", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-26", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-27", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-28", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-29", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-3", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-30", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-31", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-32", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-33", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-34", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-35", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-36", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-38", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-4", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-5", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-6", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-7", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-8", type=founder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
    individual="2171-JLH-9", type=nonfounder
    {
      genotype="A/A", penetrance=0.333333, posterior_genotype=0.25
      genotype="A/B", penetrance=0.333333, posterior_genotype=0.5
      genotype="B/B", penetrance=0.333333, posterior_genotype=0.25
    }
  }
}
