##############################################################################
##############################################################################
#
#                          INFOQC v0.0.1; 14 Jul 2015 
#
# Remember you have agreed to add an appropriate statement (including the
# NIH grant number) under "acknowledgments" in any publication of results
# obtained by using this program. Suggested wording is:
#
# "(Some of)The results of this paper were obtained by using the software
# package InfoQC, which was supported by the National Research Foundation of
# Korea Grant funded by the Korean Government (NRF-2014S1A2A2028559)."
#
##############################################################################
##############################################################################

cOption, L_defOpt = 61
option 1 : --ped mode = 0
option 2 : et.ped mode = 39
option 3 : --vcf mode = 0
option 4 : et.vcf mode = 40
option 5 : --header mode = 0
[Treat 1=case/0=control for binary phenotype(`--1case`)] allocated default value `0`
[Treat 1=female/0=male for sex encoding(`--1sex`)] allocated default value `0`
[Genetic model used in the dataset(`--model`)] allocated default value `additive`
[Number of threads used in analysis(`--thread`)] allocated default value `1`
[Verbose output(`--verbose`)] allocated default value `0`
[String for genotype missingness(`--mispheno`)] allocated default value `-9`
[Output prefix(`--misgeno`)] allocated default value `0`
[Print help information(`--out`)] allocated default value `infoqc`

exe path:
exe command: ../../infoqc --ped et.ped --vcf et.vcf --header

Reading Pedigree File....................................................
              from et.ped................................................done.
Reading Variant Calling Format (VCF) File................................
              from et.vcf37 samples found in header, 0 filtered
[867] variants scanned
[0] variants scanned
[798/867] variants and [37/37] samples loaded
................................................done.
Generating pedigree data information.....................................done.
Generating trait correlation information.................................done.
Generating marker data information.......................................done.

Analysis complete!

