###############################################################################
###############################################################################
#
#              [ONETOOL v0.0.1; 06 Jul 2016] -- 6 Jul 2016 03:44:50
#
# Remember you have agreed to add an appropriate statement (including the
# NIH grant number) under "acknowledgments" in any publication of results
# obtained by using this program. Suggested wording is:
#
# "(Some of)The results of this paper were obtained by using the software
# package ONETOOL, which was supported by the National Research Foundation
# of Korea Grant funded by Korean Government (NRF-2014S1A2A2028559)."
#
###############################################################################
###############################################################################

exe path:
exe command: ../../onetool --vcf et_simple.vcf --fam et_noloop2.fam --pheno et_noloop2.pheno --pname ET,AGE --fcor


Family structure information :

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             2171-JLH-1    M         0             0           
     1             2171-JLH-10   M         0             0           
     1             2171-JLH-11   F         0             0           
     1             2171-JLH-12   M         2171-JLH-10   2171-JLH-11 
     1             2171-JLH-13   F         0             0           
     1             2171-JLH-14   F         0             0           
     1             2171-JLH-15   M         0             0           
     1             2171-JLH-16   M         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-17   F         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-18   M         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-19   F         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-2    F         0             0           
     1             2171-JLH-20   F         2171-JLH-15   2171-JLH-32 
     1             2171-JLH-21   M         2171-JLH-12   2171-JLH-13 
     1             2171-JLH-22   F         2171-JLH-12   2171-JLH-13 
     1             2171-JLH-23   M         2171-JLH-15   2171-JLH-32 
     1             2171-JLH-24   M         2171-JLH-18   2171-JLH-8  
     1             2171-JLH-25   M         2171-JLH-17   2171-JLH-7  
     1             2171-JLH-26   F         2171-JLH-28   2171-JLH-29 
     1             2171-JLH-27   F         2171-JLH-28   2171-JLH-29 
     1             2171-JLH-28   M         2171-JLH-10   2171-JLH-11 
     1             2171-JLH-29   F         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-3    M         0             0           
     1             2171-JLH-30   M         2171-JLH-14   2171-JLH-16 
     1             2171-JLH-31   F         2171-JLH-15   2171-JLH-32 
     1             2171-JLH-32   F         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-33   M         2171-JLH-5    2171-JLH-6  
     1             2171-JLH-34   M         0             0           
     1             2171-JLH-35   M         2171-JLH-31   2171-JLH-34 
     1             2171-JLH-36   M         2171-JLH-28   2171-JLH-29 
     1             2171-JLH-38   F         2171-JLH-17   2171-JLH-7  
     1             2171-JLH-4    F         2171-JLH-1    2171-JLH-2  
     1             2171-JLH-5    M         0             0           
     1             2171-JLH-6    F         2171-JLH-3    2171-JLH-4  
     1             2171-JLH-7    M         0             0           
     1             2171-JLH-8    F         0             0           
     1             2171-JLH-9    M         2171-JLH-1    2171-JLH-2  


Phenotypes :

     PED. ID       IND. ID       ET                    AGE                 
     ------------  ------------  --------------------  --------------------
     1             2171-JLH-1    0                     19                  
     1             2171-JLH-10   -9                    23                  
     1             2171-JLH-11   -9                    29                  
     1             2171-JLH-12   1                     45                  
     1             2171-JLH-13   0                     88                  
     1             2171-JLH-14   0                     57                  
     1             2171-JLH-15   0                     33                  
     1             2171-JLH-16   1                     23                  
     1             2171-JLH-17   1                     99                  
     1             2171-JLH-18   1                     12                  
     1             2171-JLH-19   1                     27                  
     1             2171-JLH-2    0                     28                  
     1             2171-JLH-20   0                     33                  
     1             2171-JLH-21   1                     67                  
     1             2171-JLH-22   0                     34                  
     1             2171-JLH-23   1                     67                  
     1             2171-JLH-24   1                     89                  
     1             2171-JLH-25   1                     45                  
     1             2171-JLH-26   0                     56                  
     1             2171-JLH-27   1                     67                  
     1             2171-JLH-28   0                     78                  
     1             2171-JLH-29   1                     54                  
     1             2171-JLH-3    0                     45                  
     1             2171-JLH-30   1                     32                  
     1             2171-JLH-31   1                     34                  
     1             2171-JLH-32   1                     23                  
     1             2171-JLH-33   0                     43                  
     1             2171-JLH-34   0                     32                  
     1             2171-JLH-35   1                     34                  
     1             2171-JLH-36   1                     55                  
     1             2171-JLH-38   0                     34                  
     1             2171-JLH-4    1                     30                  
     1             2171-JLH-5    0                     16                  
     1             2171-JLH-6    1                     55                  
     1             2171-JLH-7    0                     49                  
     1             2171-JLH-8    0                     33                  
     1             2171-JLH-9    1                     67                  


