#==========================================================================
# Makefile for oneTool
#
#  Author:  Yeunjoo E. Song (yeunjoo.song@gmail.com)
#
#  History: Initial implementation                        - yes Nov 24 2014
#           Add compilation features and its 1st app. R   - syl Oct 10 2016
#
#  Notes:   Global Configuration for the make system
#
#  Copyright (c) 2014  Sungho Won
#    All Rights Reserved
#==========================================================================


# Grab the architecture name (generated by the configure script)

include $(ONETOOLROOT)/config/arch

# Compilation features
USE_R = 1 

# Set default BUILD to DEBUG:

BUILD = RELEASE 

# Grab the various directories required:

INSTALL_DIR = $(ONETOOLROOT)/../release/$(ARCH)
BASE_DIR    = $(shell cd $(ONETOOLROOT); pwd)
OFFSET_DIR  = $(shell pwd | sed -e "s,$(BASE_DIR)/,,")
PREV_DIR    = $(shell cd ..; pwd)
CURRENT_DIR = $(shell pwd | sed -e "s,$(PREV_DIR)/,,")
TARGET_BASE = $(ONETOOLROOT)/targets/$(ARCH)

ifeq ($(TARGET_BASE),)

blow_up:
	@echo No target directory.  Please Configure before running make

endif

TARGET_DIR = $(TARGET_BASE)/$(OFFSET_DIR)
BUILDDIR   = $(TARGET_DIR)

# Get architecture-specific options:

include $(ONETOOLROOT)/config/$(ARCH)/Global.make

# Set up macros for library includes:

LIB_CORE           = -lglobal -lutil
LIB_SAGE           = -llodlink -lsegreg -lfcor -lpedinfo -lmaxfun -lmlocus -lrped -lmped -lglobalsage $(LIB_CORE)
LIB_IO             = -linput -loutput $(LIB_SAGE)
LIB_WISARD         = -lanalyses $(LIB_IO)
LIB_R              =
CXXFLAGS_R         =
ifeq ($(strip $(USE_R)), 1)
	LIB_R      = -lR
	LDLIBS_R   = -ldl 
	CXXFLAGS_R = -DUSE_R
endif
LIB_APP            = -lapp $(LIB_WISARD) $(LIB_R)
LIB_ALL            = $(LIB_APP)

# Set architecture-independent options:

RELEASE.CFLAGS   := $(RELEASE.CFLAGS) -DONETOOL_LICENSED
RELEASE.CXXFLAGS := -static $(RELEASE.CXXFLAGS) -DONETOOL_LICENSED -DWISARD_LOG_NO_FUNC

# Define release version (see $(ONETOOLROOT)/c++/app/Licenser.cpp for implementation details)

MAIN_VERSION  = 1
SUB_VERSION   = 0
MICRO_VERSION = 0
BETA_VERSION  = 0

CXXFLAGS := $(CXXFLAGS) $(CXXFLAGS_R) -DONETOOL_MAIN_VERSION=$(MAIN_VERSION) -DONETOOL_SUB_VERSION=$(SUB_VERSION) -DONETOOL_MICRO_VERSION=$(MICRO_VERSION) -DONETOOL_BETA_VERSION=$(BETA_VERSION) -I$(R_INCLUDE_DIR)

# Add autotrace declaration:

ifeq ($(AUTOTRACE), ON)
	CXXFLAGS := $(CXXFLAGS) -DAUTOTRACE_ON
endif
